name: hazards_landslides_environments
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - _x86_64-microarch-level=3
  - aom=3.9.1
  - argcomplete=3.6.3
  - attrs=26.1.0
  - aws-c-auth=0.10.1
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.2
  - aws-c-event-stream=0.6.0
  - aws-c-http=0.10.12
  - aws-c-io=0.26.3
  - aws-c-mqtt=0.15.2
  - aws-c-s3=0.11.5
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.10
  - aws-crt-cpp=0.37.4
  - aws-sdk-cpp=1.11.747
  - azure-core-cpp=1.16.2
  - azure-identity-cpp=1.13.3
  - azure-storage-blobs-cpp=12.16.0
  - azure-storage-common-cpp=12.12.0
  - azure-storage-files-datalake-cpp=12.14.0
  - backports.zstd=1.3.0
  - blosc=1.21.6
  - bokeh=3.9.0
  - boto3=1.42.77
  - botocore=1.42.77
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.6
  - c-blosc2=2.23.1
  - ca-certificates=2026.2.25
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cartopy=0.25.0
  - cdsapi=0.7.7
  - certifi=2026.2.25
  - cffi=2.0.0
  - cfgv=3.5.0
  - charls=2.4.3
  - charset-normalizer=3.4.6
  - click=8.3.1
  - cloudpickle=3.1.2
  - configobj=5.0.9
  - contourpy=1.3.2
  - cvxopt=1.3.3
  - cycler=0.12.1
  - cytoolz=1.1.0
  - dask=2024.8.2
  - dask-core=2024.8.2
  - dask-expr=1.1.13
  - dask-jobqueue=0.9.0
  - dav1d=1.2.1
  - distlib=0.4.0
  - distributed=2024.8.2
  - donfig=0.8.1.post1
  - dsdp=5.8
  - eccodes=2.46.0
  - ecmwf-datastores-client=0.5.0
  - fftw=3.3.10
  - filelock=3.25.2
  - fonttools=4.62.0
  - freeglut=3.2.2
  - freetype=2.14.3
  - freexl=2.0.0
  - fsspec=2026.2.0
  - gdal=3.12.3
  - geos=3.14.1
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - glpk=5.0
  - gmp=6.3.0
  - gsl=2.7
  - h2=4.3.0
  - h5py=3.16.0
  - hdf4=4.2.15
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=78.3
  - identify=2.6.18
  - idna=3.11
  - imagecodecs=2026.3.6
  - imageio=2.37.0
  - importlib-metadata=8.8.0
  - importlib_metadata=8.8.0
  - jasper=4.2.9
  - jinja2=3.1.6
  - jmespath=1.1.0
  - joblib=1.5.3
  - json-c=0.18
  - jxrlib=1.1
  - keyutils=1.6.3
  - kiwisolver=1.5.0
  - krb5=1.22.2
  - lazy-loader=0.5
  - lazy_loader=0.5
  - lcms2=2.18
  - ld_impl_linux-64=2.45.1
  - lerc=4.1.0
  - libabseil=20260107.1
  - libaec=1.1.5
  - libamd=3.3.3
  - libarchive=3.8.6
  - libarrow=23.0.1
  - libarrow-acero=23.0.1
  - libarrow-compute=23.0.1
  - libarrow-dataset=23.0.1
  - libarrow-substrait=23.0.1
  - libavif16=1.4.1
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libbtf=2.3.2
  - libcamd=3.3.3
  - libcblas=3.11.0
  - libccolamd=3.3.4
  - libcholmod=5.3.1
  - libcolamd=3.3.4
  - libcrc32c=1.1.2
  - libcurl=8.19.0
  - libcxsparse=4.4.1
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.4
  - libffi=3.5.2
  - libfreetype=2.14.3
  - libfreetype6=2.14.3
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgdal-core=3.12.3
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libgoogle-cloud=3.3.0
  - libgoogle-cloud-storage=3.3.0
  - libgrpc=1.78.1
  - libhwy=1.3.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.2
  - libklu=2.3.5
  - libkml=1.3.0
  - liblapack=3.11.0
  - libldl=3.3.2
  - liblzma=5.8.2
  - libnetcdf=4.10.0
  - libnghttp2=1.68.1
  - libnsl=2.0.1
  - libopenblas=0.3.32
  - libopengl=1.7.0
  - libopentelemetry-cpp=1.26.0
  - libopentelemetry-cpp-headers=1.26.0
  - libparquet=23.0.1
  - libparu=1.0.0
  - libpng=1.6.56
  - libprotobuf=6.33.5
  - librbio=4.3.4
  - libre2-11=2025.11.05
  - librttopo=1.1.0
  - libspatialite=5.1.0
  - libspex=3.2.3
  - libspqr=4.3.4
  - libsqlite=3.52.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsuitesparseconfig=7.10.1
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libumfpack=6.3.5
  - libutf8proc=2.11.3
  - libuuid=2.41.3
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.15.2
  - libxml2-16=2.15.2
  - libxml2-devel=2.15.2
  - libxslt=1.1.43
  - libzip=1.11.2
  - libzlib=1.3.2
  - libzopfli=1.0.3
  - locket=1.0.0
  - lxml=6.0.2
  - lz4=4.4.5
  - lz4-c=1.10.0
  - lzo=2.10
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib-base=3.10.8
  - mdurl=0.1.2
  - metis=5.1.0
  - minizip=4.0.10
  - mintpy=1.6.3
  - mpfr=4.2.2
  - msgpack-python=1.1.2
  - multiurl=0.3.7
  - munkres=1.1.4
  - muparser=2.3.5
  - narwhals=2.18.1
  - ncurses=6.5
  - networkx=3.4
  - nlohmann_json=3.12.0
  - nodeenv=1.10.0
  - numpy=1.23.5
  - openjpeg=2.5.4
  - openjph=0.26.3
  - openssl=3.6.1
  - orc=2.3.0
  - packaging=26.0
  - pandas=2.3.3
  - partd=1.4.2
  - pcre2=10.47
  - pillow=12.1.1
  - pip=26.0.1
  - platformdirs=4.9.4
  - pre-commit=4.5.1
  - proj=9.8.0
  - prometheus-cpp=1.3.0
  - psutil=7.2.2
  - pthread-stubs=0.4
  - pyaps3=0.3.7
  - pyarrow=23.0.1
  - pyarrow-core=23.0.1
  - pycparser=2.22
  - pygments=2.19.2
  - pygrib=2.1.8
  - pykdtree=1.4.3
  - pykml=0.2.0
  - pyparsing=3.3.2
  - pyproj=3.7.2
  - pyresample=1.34.2
  - pyshp=3.0.3
  - pysocks=1.7.1
  - pysolid=0.3.4
  - python=3.11.15
  - python-dateutil=2.9.0.post0
  - python-discovery=1.2.1
  - python-tzdata=2025.3
  - python_abi=3.11
  - pytz=2026.1.post1
  - pywavelets=1.8.0
  - pyyaml=6.0.3
  - qhull=2020.2
  - rav1e=0.8.1
  - re2=2025.11.05
  - readline=8.3
  - requests=2.33.0
  - rich=14.3.3
  - s2n=1.7.1
  - s3transfer=0.16.0
  - scikit-image=0.25.0
  - scipy=1.15.2
  - setuptools=82.0.1
  - shapely=2.1.2
  - six=1.17.0
  - snappy=1.2.2
  - sortedcontainers=2.4.0
  - sqlite=3.52.0
  - suitesparse=7.10.1
  - svt-av1=4.0.1
  - tblib=3.2.2
  - tifffile=2026.3.3
  - tk=8.6.13
  - toolz=1.1.0
  - tornado=6.5.5
  - tqdm=4.67.3
  - typing_extensions=4.15.0
  - tzdata=2025c
  - ukkonen=1.1.0
  - unicodedata2=17.0.1
  - uriparser=0.9.8
  - urllib3=2.6.3
  - utm=0.7.0
  - virtualenv=21.2.0
  - wheel=0.46.3
  - xerces-c=3.3.0
  - xorg-libx11=1.8.13
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.7
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xyzservices=2025.11.0
  - yaml=0.2.5
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.23.0
  - zlib=1.3.2
  - zlib-ng=2.3.3
  - zstd=1.5.7
